services:

  proptech-core-service:
    image: cyberstarsng/proptech-core-service:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_CLOUD_VAULT_TOKEN: /run/secrets/vault_root_token
      SPRING_CLOUD_VAULT_URI: https://vault.cyberstarsng.com
    secrets:
      - vault_root_token
    volumes:
      - proptech_api_data:/var/lib/proptech-core-service
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        order: start-first
      placement:
        constraints:
          - node.role == manager
    labels:
      - "traefik.enable=true"

networks:
  backend:
    driver: overlay
    internal: true
  traefik-public:
    driver: overlay
    external: true

volumes:
  proptech_api_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/api-data


secrets:
  vault_root_token:
    external: true