apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: frontend-security-headers
  namespace: ingress
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    frameDeny: true
    sslRedirect: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    customFrameOptionsValue: SAMEORIGIN
    customResponseHeaders:
      X-Powered-By: ""
      Server: ""
    contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://staging.minio.s3.primecrib.app https://minio.s3.primecrib.app https://tile.openstreetmap.org https://imgproxy.primecrib.app https://staging.imgproxy.primecrib.app connect-src 'self' https://staging.api.primecrib.app https://api.primecrib.app https://staging.route.primecrib.app https://route.primecrib.app wss://staging.api.primecrib.app wss://api.primecrib.app  wss://staging.route.primecrib.app wss://route.primecrib.app https://minio.s3.primecrib.app https://staging.minio.s3.primecrib.app https://imgproxy.primecrib.app  https://staging.imgproxy.primecrib.app worker-src 'self' blob: https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com data:; object-src 'none'; base-uri 'self'; frame-ancestors 'self';"
    referrerPolicy: strict-origin-when-cross-origin
