version: "3.9"

services:

  traefik:
    image: traefik:v3.0
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - traefik_logs:/var/log/traefik
    secrets:
      - dashboard_users
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        # Dashboard Router
        - "traefik.http.middlewares.ipwhitelist.ipwhitelist.sourcerange=45.130.104.193/32"
        - "traefik.http.routers.traefik-dashboard.middlewares=dashboard-auth,ipwhitelist"

        - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.cyberstarsng.com`)"
        - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
        - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"

        # Secure the dashboard with basic auth
        - "traefik.http.middlewares.dashboard-auth.basicauth.usersfile=/run/secrets/dashboard_users"

        # Point to internal dashboard service
        - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"


# ────────────────────────────────
# LOCAL PERSISTENT VOLUMES
# ────────────────────────────────
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/postgres-data

  vault_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/vault-data

  vault_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/vault-logs

  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/minio-data

  minio_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/minio-config

  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/prometheus-data

  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/grafana-data

  traefik_letsencrypt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/traefik-letsencrypt-data

  traefik_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/traefik-data

  traefik_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/traefik-logs

  github-runner-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/github-runner-data

  rabbitmq_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/containers/storages/rabbitmq-data

networks:
  backend:
    driver: overlay
    internal: true
  traefik-public:
    driver: overlay
    external: true
  ci-network:
    driver: overlay
    external: false
    driver_opts:
      encrypted: "true"

secrets:
  db_name:
    external: true
  db_user:
    external: true
  db_password:
    external: true
  vault_root_token:
    external: true
  vault_unseal_key:
    external: true
  jwt_secret_key:
    external: true
  rabbit_password:
    external: true
  minio_root_password:
    external: true
  github_runner_token:
    external: true
  grafana_root_password:
    external: true
  dashboard_users:
    external: true
