apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: observability
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3200
    - name: otlp-grpc
      port: 4317
    - name: otlp-http
      port: 4318
  selector:
    app.kubernetes.io/name: tempo
