global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Spring Boot Applications via Docker Swarm DNS Discovery

  - job_name: 'proptech_api_prometheus'
    metrics_path: '/api/v1/actuator/prometheus'
    dns_sd_configs:
      - names:
          - 'proptech_api'
        type: 'A'
        port: 8081