# Application ExternalSecrets — synced to apps-staging and apps-prod
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: proptech-core-service-secrets
  namespace: apps-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: proptech-core-service-secrets
  dataFrom:
    - extract:
        key: apps/proptech-core-service
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: proptech-core-service-secrets
  namespace: apps-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: proptech-core-service-secrets
  dataFrom:
    - extract:
        key: apps/proptech-core-service
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gateway-service-secrets
  namespace: apps-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gateway-service-secrets
  dataFrom:
    - extract:
        key: apps/gateway-service
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gateway-service-secrets
  namespace: apps-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gateway-service-secrets
  dataFrom:
    - extract:
        key: apps/gateway-service
