# traefik.yml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# API and Dashboard
api:
  dashboard: true
  insecure: false  # Only accessible over HTTPS

# Entry Points
entryPoints:
  web:
    address: ":80"
    http:
      # Redirect HTTP → HTTPS only after certs are issued
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        options: default  # Use TLS options from dynamic config

  redis:
    address: ":6379"

# Enable ping for health checks
ping:
  entryPoint: web

# Certificate Resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: cyberstarsng@gmail.com
      storage: /acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      keyType: RSA4096
      httpChallenge:
        entryPoint: web

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-public
    watch: true
    defaultRule: "Host(`{{ normalize .Name }}.cyberstarsng.com`)"

  file:
    directory: /etc/traefik/dynamic
    watch: true

# Logging
log:
  level: INFO  # Change to DEBUG only for troubleshooting
  format: json
#  filePath: /var/log/traefik/traefik.log
  filePath: ""
  maxSize: 100
  maxBackups: 3
  maxAge: 7
  compress: true
  noColor: true

accessLog:
  format: json
  filePath: /var/log/traefik/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-599"
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop
      names:
        User-Agent: keep
        X-Forwarded-For: keep
        X-Real-Ip: keep
        X-Forwarded-Proto: keep

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
