apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cache-static-long
  namespace: ingress
spec:
  headers:
    customResponseHeaders:
      Cache-Control: "public, max-age=31536000, immutable"
