http:
  routers:
    traefik-dashboard:
      rule: Host(`staging.traefik.primecrib.app`)
      entryPoints:
        - websecure
      service: api@internal
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - dashboard-auth
        - securityHeaders

    vault-dashboard:
      rule: Host(`staging.vault.primecrib.app`)
      entryPoints:
        - websecure
      service: vault-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - securityHeaders

    rabbit-dashboard:
      rule: Host(`staging.rabbitmq.primecrib.app`)
      entryPoints:
        - websecure
      service: rabbit-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - compression
        - rateLimit
        - retry
        - buffering
        - rabbitmq-csp

    minio-dashboard:
      rule: Host(`staging.minio.primecrib.app`)
      entryPoints:
        - websecure
      service: minio-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - cacheNoStore
        - securityHeaders
        - compression
        - rateLimit
        - retry
        - circuitBreaker
        - buffering

    minio-s3:
      rule: Host(`staging.minio.s3.primecrib.app`)
      entryPoints:
        - websecure
      service: minio-s3-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - cacheStaticLong
        - securityHeaders
        - compression
        - rateLimit
        - retry
        - circuitBreaker
        - buffering

    prometheus-dashboard:
      rule: Host(`staging.prometheus.primecrib.app`)
      entryPoints:
        - websecure
      service: prometheus-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - cacheNoStore
        - dashboard-auth
        - securityHeaders
        - compression
        - rateLimit
        - retry
        - circuitBreaker
        - buffering

    grafana-dashboard:
      rule: Host(`staging.grafana.primecrib.app`)
      entryPoints:
        - websecure
      service: grafana-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - cacheNoStore
        - securityHeaders
        - compression
        - rateLimit
        - retry
        - circuitBreaker
        - buffering

    portainer-dashboard:
      rule: Host(`staging.portainer.primecrib.app`)
      entryPoints:
        - websecure
      service: portainer-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - cacheNoStore
        - securityHeaders
        - compression
        - rateLimit
        - retry
        - circuitBreaker
        - buffering

    adminer-dashboard:
      rule: Host(`staging.adminer.primecrib.app`)
      entryPoints:
        - websecure
      service: adminer-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - cacheNoStore
        - dashboard-auth
        - securityHeaders
        - compression

    redis-insight-dashboard:
      rule: Host(`staging.redis-insight.primecrib.app`)
      entryPoints:
        - websecure
      service: redis-insight-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - cacheNoStore
        - dashboard-auth
        - securityHeaders
        - compression

    imgproxy-dashboard:
      rule: Host(`staging.imgproxy.primecrib.app`)
      entryPoints:
        - websecure
      service: imgproxy-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - cacheNoStore
        - dashboard-auth
        - securityHeaders
        - compression

    haproxy-stats-dashboard:
      rule: Host(`staging.haproxy.primecrib.app`)
      entryPoints:
        - websecure
      service: haproxy-stats-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - cacheNoStore
        - dashboard-auth
        - securityHeaders
        - compression

    proptech-core-service:
      rule: Host(`staging.api.primecrib.app`)
      priority: 1
      entryPoints:
        - websecure
      service: proptech-core-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - securityHeaders
        - compression
        - rateLimit
        - retry
        - circuitBreaker
        - buffering

    proptech-gateway-service:
      rule: Host(`staging.route.primecrib.app`)
      entryPoints:
        - websecure
      service: proptech-gateway-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - securityHeaders
        - compression
        - rateLimit
        - retry
        - circuitBreaker
        - buffering

    proptech-admin:
      rule: Host(`staging.admin.primecrib.app`)
      entryPoints:
        - websecure
      service: proptech-admin-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - frontendSecurityHeaders
        - compression
        - rateLimit
        - retry
        - buffering

    proptech-app:
      rule: Host(`staging.primecrib.app`)
      entryPoints:
        - websecure
      service: proptech-app-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - frontendSecurityHeaders
        - compression
        - rateLimit
        - retry
        - buffering

    proptech-pitch:
      rule: Host(`pitch.primecrib.app`)
      entryPoints:
        - websecure
      service: proptech-pitch-service
      tls:
        certResolver: letsencrypt
        options: default
      middlewares:
        - frontendSecurityHeaders
        - compression
        - rateLimit
        - retry
        - buffering

  services:
    rabbit-service:
      loadBalancer:
        servers:
          - url: "http://rabbitmq:15672"

    minio-service:
      loadBalancer:
        servers:
          - url: "http://minio:9001"

    minio-s3-service:
      loadBalancer:
        servers:
          - url: "http://minio:9000"

    vault-service:
      loadBalancer:
        serversTransport: vaultTransport
        servers:
          - url: "https://vault:8200"

    prometheus-service:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"

    grafana-service:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

    portainer-service:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"

    adminer-service:
      loadBalancer:
        servers:
          - url: "http://adminer:8080"

    redis-insight-service:
      loadBalancer:
        servers:
          - url: "http://redis-insight:5540"

    imgproxy-service:
      loadBalancer:
        servers:
          - url: "http://imgproxy:8080"

    haproxy-stats-service:
      loadBalancer:
        servers:
          - url: "http://haproxy:8404"

    proptech-core-service:
      loadBalancer:
        servers:
          - url: "http://proptech_api:8081"
        sticky:
          cookie:
            name: "proptech_sticky"
            secure: true
            httpOnly: true

    proptech-gateway-service:
      loadBalancer:
        servers:
          - url: "http://proptech_gateway:8008"
        sticky:
          cookie:
            name: "proptech_gateway_sticky"
            secure: true
            httpOnly: true

    proptech-admin-service:
      loadBalancer:
        servers:
          - url: "http://proptech_admin:3000"
        sticky:
          cookie:
            name: "proptech_admin_sticky"
            secure: true
            httpOnly: true

    proptech-app-service:
      loadBalancer:
        servers:
          - url: "http://proptech_app:3000"
        sticky:
          cookie:
            name: "proptech_app_sticky"
            secure: true
            httpOnly: true

    proptech-pitch-service:
      loadBalancer:
        servers:
          - url: "http://proptech_pitch:3000"
        sticky:
          cookie:
            name: "proptech_pitch_sticky"
            secure: true
            httpOnly: true

  serversTransports:
    vaultTransport:
      insecureSkipVerify: true

tcp:
  routers:
    minio-tcp:
      entryPoints:
        - websecure
      rule: "HostSNI(`staging.minio.s3.primecrib.app`)"  # Staging SNI with prefix
      service: minio-tcp
      tls:
        passthrough: true
    rabbit-tcp:
      entryPoints:
        - websecure
      rule: "HostSNI(`staging.rabbitmq.primecrib.app`)"  # Staging SNI with prefix
      service: rabbit-tcp
      tls:
        certResolver: letsencrypt
        options: default

  services:
    minio-tcp:
      loadBalancer:
        servers:
          - address: "minio:9000"
    rabbit-tcp:
      loadBalancer:
        servers:
          - address: "rabbitmq:5672"

