http:
  routers:
    traefik-dashboard:
      rule: Host(`traefik.cyberstarsng.com`)
      entryPoints:
        - websecure
      service: api@internal
      tls:
        certResolver: letsencrypt
      middlewares:
        - dashboard-auth
        - dashboard-whitelist

    vault-dashboard:
      rule: Host(`vault.cyberstarsng.com`)
      entryPoints:
        - websecure
      service: vault-service
      tls:
        certResolver: letsencrypt
      middlewares:
        - vault-auth
        - vault-whitelist

    rabbit-dashboard:
      rule: Host(`rabbit.cyberstarsng.com`)
      entryPoints:
        - websecure
      service: rabbit-service
      tls:
        certResolver: letsencrypt
      middlewares:
        - rabbit-auth
        - rabbit-whitelist

  services:

    vault-service:
      loadBalancer:
        servers:
          - url: "http://vault:8200"

    rabbit-service:
      loadBalancer:
        servers:
          - url: "http://rabbitmq:15672"
