http:
  routers:
    traefik-dashboard:
      rule: Host(`traefik.cyberstarsng.com`)
      entryPoints:
        - websecure
      service: api@internal
      tls:
        certResolver: letsencrypt
      middlewares:
        - dashboard-auth

    vault-dashboard:
      rule: Host(`vault.cyberstarsng.com`)
      entryPoints:
        - websecure
      service: vault-service
      tls:
        certResolver: letsencrypt

    rabbit-dashboard:
      rule: Host(`rabbit.cyberstarsng.com`)
      entryPoints:
        - websecure
      service: rabbit-service
      tls:
        certResolver: letsencrypt

    minio-dashboard:
      rule: Host(`minio.cyberstarsng.com`)
      entryPoints:
        - websecure
      service: minio-service
      tls:
        certResolver: letsencrypt

    proptech-core-service:
      rule: Host(`api.cyberstarsng.com`)
      entryPoints:
        - websecure
      service: proptech-core-service
      tls:
        certResolver: letsencrypt

  services:

    rabbit-service:
      loadBalancer:
        servers:
          - url: "http://rabbitmq:15672"

    minio-service:
      loadBalancer:
        servers:
          - url: "http://minio:9001"

    vault-service:
      loadBalancer:
        servers:
          - url: "http://vault:8200"

    proptech-core-service:
      loadBalancer:
        servers:
          - url: "http://proptech-core_app:8081"

tcp:
  routers:
    redis:
      entryPoints:
        - redis
      rule: "HostSNI(`redis.cyberstarsng.com`)"  # Required for TLS
      service: redis-tcp
      tls:
        passthrough: true

  services:
    redis-tcp:
      loadBalancer:
        servers:
          - address: "redis:6379"
