apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis-replication.yaml
  - redis-sentinel.yaml

configMapGenerator:
  - name: redis-config
    files:
      - redis.conf=../../../redis/redis.conf
