apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisSentinel
metadata:
  name: proptech-redis-sentinel
  namespace: platform-data
spec:
  clusterSize: 3
  redisReplicationName: proptech-redis
  kubernetesConfig:
    image: redis:8.2-alpine
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    redisSecret:
      name: redis-credentials
      key: password
