apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: proptech-minio
  namespace: platform-data
spec:
  image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
  credsSecret:
    name: minio-credentials
  pools:
    - servers: 4
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: longhorn
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 50Gi
      resources:
        requests:
          cpu: "1"
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 2Gi
  requestAutoCert: false
  features:
    bucketDNS: false
  exposeServices:
    console: true
    minio: true
