apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
  namespace: platform-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
        - name: redis-insight
          image: redis/redisinsight:3.0.2
          ports:
            - containerPort: 5540
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-insight-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-insight-data
  namespace: platform-tools
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight
  namespace: platform-tools
spec:
  selector:
    app: redis-insight
  ports:
    - port: 5540
