apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml
  - scheduled-backup.yaml
  - pooler.yaml

configMapGenerator:
  - name: proptech-postgres-init
    files:
      - init.sql.template=../../../postgres/init.sql.template
