apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: proptech-pg-daily
  namespace: platform-data
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: proptech-pg
  method: barmanObjectStore
